port: "5432"
host: "localhost"
db:
  username: "postgres"
  password: "postgres"
  host: "database"
  port: "5432"
  dbname: "uir_draft"
  sslmode: "disable"
#db:
#  username: "postgres"
#  password: "admin"
#  host: "host.docker.internal"
#  port: "5432"
#  dbname: "uir_draft"
#  sslmode: "disable"
